name: workflow_dispatch sample

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: "choice variable"
        required: true
        default: "b"
        options:
          - "a"
          - "b"
          - "c"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: print log
        run: echo "Hello!"

      - name: choice test a
        if: ${{ inputs.choice }} == 'a'
        run: echo "choice=${{ inputs.choice }}"

      - name: choice test b
        if: ${{ inputs.choice }} == 'b'
        run: echo "choice=${{ inputs.choice }}"
